# Mapping for remote (using Adafruit mini-remote (NEC style)
mapping = {
    "0xbf09": "Enter",
    "0xbf08": "Left",
    "0xbf0a": "Right",
    "0xbf05": "Up",
    "0xbf0d": "Down",
    "0xbf04": "Setup",
    "0xbf06": "Mode",
    "0xbf0c": "0",
    "0xbf10": "1",
    "0xbf11": "2",
    "0xbf12": "3",
    "0xbf14": "4",
    "0xbf15": "5",
    "0xbf16": "6",
    "0xbf18": "7",
    "0xbf19": "8",
    "0xbf1a": "9",
    "0xbf0e": "Back",
    "0xbf00": "Vol_down",
    "0xbf02": "Vol_up",
    "0xbf01": "Play",
}

mapping2 = {
    "KEY_VOLUMEDOWN": "Vol_down",
    "KEY_PLAYPAUSE": "Play",
    "KEY_VOLUMEUP": "Vol_up",
    "KEY_SETUP": "Setup",
    "KEY_UP": "Up",
    "KEY_STOP": "Mode",
    "KEY_LEFT": "Left",
    "KEY_ENTER": "Enter",
    "KEY_RIGHT": "Right",
    "KEY_0": "0",
    "KEY_DOWN": "Down",
    "KEY_BACK": "Back",
    "KEY_1": "1",
    "KEY_2": "2",
    "KEY_3": "3",
    "KEY_4": "4",
    "KEY_5": "5",
    "KEY_6": "6",
    "KEY_7": "7",
    "KEY_8": "8",
    "KEY_9": "9",
}
